### ISSUE TITLE
[Question] Questions about Blueprint

### ISSUE THREAD

**Issue by hooliooo** [square/Blueprint#10]
Hi there!

A colleague linked me this repo and I've been browsing the source code. Just some questions:

* This doesn't use AutoLayout right? Doesn't seem like it from an initial glance. 
* Are you reusing views in a scenario like UITableView/UICollectionView? LayoutKit by LinkedIn does this.

Looking forward to see how this library evolves 👍  Awesome job

**Comment by timdonnelly** [comment]
Thanks for checking this out!

- It does not use AutoLayout (it uses specific (read: simple) layout types at each level of the tree)
- Blueprint reuses views between updates *if* they exist at the same location within the element hierarchy. Does this answer you question, or are you asking about the use of table views or collection views with Blueprint specifically?

**Comment by hooliooo** [comment]
Yes it does. Thank you :)
