### ISSUE TITLE
[Question] How blueprint manages data change and trigger view update

### ISSUE THREAD

**Issue by shuoli84** [square/Blueprint#11]
The doc mentioned auto ui update for data change, but didn't see this in tutorial.

**Comment by timdonnelly** [comment]
Blueprint supports updating the hierarchy at any time – but it is up to the consuming app to *tell* it to update (there is no automatic data binding or anything).

Your code might look something like this:

```swift

final class MyViewController: UIViewController {

    /// etc... 

    private let blueprintView: BlueprintView

    // Hypothetical delegate method
    func dataDidChange(data: NewData) {
       blueprintView.element = MyRootElement(data: data)
    }

}

```

**Comment by shuoli84** [comment]
Got it. Thanks.
