### ISSUE TITLE
Stack layout should measure cross axis after layout axis has been allotted

### ISSUE THREAD

**Issue by watt** [square/Blueprint#58]
Stack layout currently measures its children only once, using the stack's entire bounds as a constraint. These basis sizes are then used for the cross axis sizes, while the layout axis sizes are adjusted according to the child priorities.

For elements like a `Label` with text wrapping, where the height depends on the width, this can result in undesirable cross axis measurements.

Here's an example:

```swift
struct TestElement: ProxyElement {
    var elementRepresentation: Element {
        return Column { column in
            column.verticalUnderflow = .justifyToCenter
            column.horizontalAlignment = .fill

            column.add(child: row(withMargin: 0))
            column.add(child: row(withMargin: 50))
        }
    }

    func row(withMargin margin: CGFloat) -> Element {
        return Row { row in
            row.horizontalOverflow = .condenseProportionally

            row.add(
                growPriority: 0,
                shrinkPriority: 0,
                child: Spacer(size: CGSize(width: margin, height: 0)))

            row.add(
                growPriority: 1,
                shrinkPriority: 1,
                child: Label(text: "This is a long label for testing. It takes up 2 lines if there are no margins, but needs 3 if we add some margins."))

            row.add(
                growPriority: 0,
                shrinkPriority: 0,
                child: Spacer(size: CGSize(width: margin, height: 0)))
        }
    }
}
```

<img width="430" alt="Screen Shot 2020-02-25 at 12 03 54 PM" src="https://user-images.githubusercontent.com/100192/75283312-761de300-57c7-11ea-92b2-097af3040b32.png">

In the second instance, the label should ideally be wrapped onto 3 lines. However, its height measurement is the same as the first instance, and does not take into account the adjusted width. It ends up truncated.

To fix this, I think we should re-measure children after determining the layout axis, and use those measurements for the cross axis sizes, rather than the basis sizes.

**Comment by kyleve** [comment]
So, this is a bit interesting because layout and measurement are two separate passes... I think to fix this locally within stack, we want to make an internal method which does layout which both `Layout` methods defer to – this lets us centralize logic. I also think the idea of doing underflow and overflow _after_ sizing happens is wrong – it fundamentally ends up breaking cases like this. I think we need to calculate underflow vs. overflow as we're measuring to then re-calc sizing.

**Comment by kyleve** [comment]
Working on a rough prototype of a fix for this here, https://github.com/square/Blueprint/pull/60. Not ready for review yet, but I think it resolves the base issue... hopefully?
