### ISSUE TITLE
Proposal: SwiftUI-like EnvironmentValues

### ISSUE THREAD

**Issue by watt** [square/Blueprint#61]
I've prototyped a potential implementation of an environmental context like SwiftUI's `@Environment` functionality. I'd like to get some feedback on this approach before opening a PR.

Like SwiftUI, it features an extensible, strongly-typed dictionary, where keys are types, and each key has a default value. Environment modifications in outer elements cascade to the contained elements at layout time without the two having any knowledge of each other.

Unlike SwiftUI, it does not use property wrappers, and is less magical. Instead there is a new protocol `ContextElement` that works just like `ProxyElement`, but instead of an `elementRepresentation` property it has a function:

```swift
public protocol ContextElement: Element {
    func elementRepresentation(in environment: Environment) -> Element
}
```

To accomplish this I added a new `ContentStorage` implementation for `ElementContent` that holds a closure, and defers building its child elements until layout time. By deferring until layout time, we can use the layout pass to cascade an `Environment` instance through the entire tree.

This strategy requires building children twice: once for measuring and once for layout. Leaf nodes might be built numerous times if there are elements upstream in the tree that measure their children for layout.

## Prototype

Because the environment is required to build children, and building children is required for measuring, this change affects all `Measurable`s. I tried two implementations.

https://github.com/square/Blueprint/tree/watt/environment-api-measurable

This branch changes `Measurable` and adds an `Environment` argument.

https://github.com/square/Blueprint/tree/watt/environment-api-nonmeasurable

This branch does not change `Measurable`. Some types simply no longer conform. `ElementContent` has a function like this instead:

```swift
func measurable(in environment: Environment) -> Measurable 
```

The second approach had a smaller impact, but I could see doing it either way.

## Example

[This commit](https://github.com/square/Blueprint/commit/755e242c57f9efec44b22b900593d7a9bcbecbad) contains an example use in the sample app.

**Comment by kyleve** [comment]
Also similar: ViewEnvironment in Workflow: https://github.com/square/workflow/pull/999/files

**Comment by watt** [comment]
Yeah, I believe they are similar ideas. ViewEnvironment cascades down the workflow tree, and this cascades down an element tree. You could use ViewEnvironment as the source of values to a Blueprint Environment.

**Comment by kyleve** [comment]
Can we an open a PR in this repo for review + comment? I find this the easiest way to absorb and provide feedback – include WIP in the title so it's more obvious what it's for?

**Comment by watt** [comment]
Sure, I didn't open a PR mainly because I have 2 branches (linked above) with different implementations.  But I've opened WIP PRs for each of them.

#62 

#63 

Only one of them has the example usage, and neither one of them have updated tests.

**Comment by mattfaluotico** [comment]
When would it be best to use Environment vars over just passing in the property in the initializer? It's not easy to see that an Element changes based on a particular Env variable (Unless that's okay) but it's fairly implied when it's a part of the initializer. They seem to behave the same way?

**Comment by kyleve** [comment]
Eg, device information like safeAreaInsets.

**Comment by watt** [comment]
@mattfaluotico You're correct, using Environment does hide some behavior that could be made explicit by putting it in the initializer. You'd definitely want to use this sparingly, and continue to be explicit with most properties. It works best with "global" values that are cumbersome to explicitly pass down through an entire element tree. Safe area insets is a good example. Also, potentially things like:

- LTR direction
- Pixel density
- dark/light mode
- content size category
- locale

See [SwiftUI's EnvironmentValues](https://developer.apple.com/documentation/swiftui/environmentvalues) for some more examples.

**Comment by bencochran** [comment]
(Except `managedObjectContext`, I hate that they put that into `EnvironmentValues`.)

**Comment by watt** [comment]
To make this easier to digest and review, I have cleaned up one of the prototypes into a full implementation (#63) and deleted the other one.
